import { VoiceRoom, Gift, SoundBoardEffect, User } from '../types';
import { getXpForLevel } from './xpUtils';

export const CURRENT_USER: User = {
  id: 'user_me',
  name: 'Shiyam Boss 👑',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  level: 42,
  xp: getXpForLevel(42) + 350,
  vipLevel: 6,
  coins: 52400,
  gems: 1200,
  frameUrl: 'border-amber-400 shadow-[0_0_15px_rgba(251,191,36,0.8)]',
  entryVehicle: 'Lamborghini Golden Flame',
  bio: 'Hapi Party Host & Gold VIP 👑 | Adda Lover',
  gender: 'male',
};

export const MOCK_USERS: User[] = [
  {
    id: 'user_1',
    name: 'Aira AI 🤖',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    level: 99,
    xp: getXpForLevel(99) + 2000,
    vipLevel: 8,
    coins: 999999,
    gems: 50000,
    frameUrl: 'border-purple-500 shadow-[0_0_20px_rgba(168,85,247,0.9)]',
    bio: 'Official Voice Room AI Host & Entertainer ✨',
    gender: 'female',
  },
  {
    id: 'user_2',
    name: 'Anika Khan 💖',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    level: 35,
    xp: getXpForLevel(35) + 120,
    vipLevel: 4,
    coins: 18500,
    gems: 450,
    bio: 'Love Music & Good Vibes 🎶',
    gender: 'female',
  },
  {
    id: 'user_3',
    name: 'Tanvir Prince 🚗',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    level: 50,
    xp: getXpForLevel(50) + 800,
    vipLevel: 7,
    coins: 89000,
    gems: 3400,
    bio: 'Supercar Collector & Party King ⚡',
    gender: 'male',
  },
  {
    id: 'user_4',
    name: 'Nusrat Voice 🎤',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    level: 28,
    xp: getXpForLevel(28) + 40,
    vipLevel: 3,
    coins: 12400,
    gems: 210,
    bio: 'Singing is my passion 🎧',
    gender: 'female',
  },
  {
    id: 'user_5',
    name: 'Riyad Gamer 🎮',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    level: 19,
    xp: getXpForLevel(19) + 90,
    vipLevel: 2,
    coins: 6300,
    gems: 80,
    bio: 'Pubg & Ludo champion 🏆',
    gender: 'male',
  },
];

export const GIFTS_CATALOG: Gift[] = [
  {
    id: 'gift_rose',
    name: 'Gold Rose',
    category: 'popular',
    price: 10,
    icon: '🌹',
    animationType: 'confetti',
    description: 'A glowing golden rose of appreciation',
  },
  {
    id: 'gift_heart',
    name: 'Love Heart',
    category: 'popular',
    price: 50,
    icon: '💖',
    animationType: 'confetti',
    description: 'Send love to your favorite speaker',
  },
  {
    id: 'gift_ring',
    name: 'Diamond Ring',
    category: 'luxury',
    price: 200,
    icon: '💎',
    animationType: 'diamond_rain',
    description: 'Sparkling diamond ring for special seats',
  },
  {
    id: 'gift_crown',
    name: 'Royal Crown',
    category: 'luxury',
    price: 500,
    icon: '👑',
    animationType: 'diamond_rain',
    description: 'Crown the king or queen of the voice room',
  },
  {
    id: 'gift_car',
    name: 'Bugatti Supercar',
    category: 'supercar',
    price: 1500,
    icon: '🏎️',
    animationType: 'car_drive',
    description: 'Full-screen racing supercar animation with engine sound',
  },
  {
    id: 'gift_yacht',
    name: 'Luxury Yacht',
    category: 'supercar',
    price: 3000,
    icon: '🛥️',
    animationType: 'car_drive',
    description: 'Cruise the party ocean in style',
  },
  {
    id: 'gift_dragon',
    name: 'Fire Dragon',
    category: 'magic',
    price: 5000,
    icon: '🐉',
    animationType: 'dragon_fire',
    description: 'Epic fiery dragon breathing flames across the room',
  },
  {
    id: 'gift_galaxy',
    name: 'Galaxy Castle',
    category: 'magic',
    price: 10000,
    icon: '🏰',
    animationType: 'galaxy',
    description: 'The ultimate luxury castle gift with full-screen fireworks',
  },
];

export const SOUNDBOARD_EFFECTS: SoundBoardEffect[] = [
  { id: 'fx_applause', name: 'Applause', icon: '👏', type: 'applause' },
  { id: 'fx_laughter', name: 'Laughter', icon: '😂', type: 'laughter' },
  { id: 'fx_cheer', name: 'Party Cheer', icon: '🎉', type: 'cheer' },
  { id: 'fx_drumroll', name: 'Drum Roll', icon: '🥁', type: 'drumroll' },
  { id: 'fx_horn', name: 'Air Horn', icon: '🎺', type: 'horn' },
  { id: 'fx_coin', name: 'Coin Drop', icon: '🪙', type: 'coin' },
];

export const SAMPLE_ROOMS: VoiceRoom[] = [
  {
    id: 'room_101',
    title: '🇧🇩 Dhaka Romantic Adda & Live Songs 🎶',
    notice: 'Welcome to Dhaka Adda! Mic seats open for singers. Keep it clean & respectful! ❤️',
    host: CURRENT_USER,
    category: 'Bengali Adda',
    bgTheme: 'neon_purple',
    bgmPlaying: true,
    currentTrack: 'Lo-Fi Sunset Lounge',
    isLocked: false,
    onlineCount: 428,
    giftValueToday: 48500,
    tags: ['Bengali', 'Singing', 'Late Night', 'Friendly'],
    seats: [
      { id: 0, userId: CURRENT_USER.id, user: CURRENT_USER, isMuted: false, isLocked: false, isSpeaking: true, speakingVolume: 65, title: 'Owner 👑' },
      { id: 1, userId: MOCK_USERS[0].id, user: MOCK_USERS[0], isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0, title: 'AI Co-Host 🤖' },
      { id: 2, userId: MOCK_USERS[1].id, user: MOCK_USERS[1], isMuted: false, isLocked: false, isSpeaking: true, speakingVolume: 80, title: 'VIP Singer 🎤' },
      { id: 3, userId: MOCK_USERS[2].id, user: MOCK_USERS[2], isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0, title: 'Top Giver 👑' },
      { id: 4, userId: MOCK_USERS[3].id, user: MOCK_USERS[3], isMuted: true, isLocked: false, isSpeaking: false, speakingVolume: 0, title: 'Guest' },
      { id: 5, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 6, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 7, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
    ],
  },
  {
    id: 'room_102',
    title: '🔥 VIP Night Club & Luxury Car Show 🏎️',
    notice: 'Big Givers & Luxury Car battle! Win galaxy castle badges tonight! 💎',
    host: MOCK_USERS[2],
    category: 'Party',
    bgTheme: 'luxury_gold',
    bgmPlaying: true,
    currentTrack: 'Club Electro Party',
    isLocked: false,
    onlineCount: 890,
    giftValueToday: 120500,
    tags: ['Party', 'Gifting', 'VIP', 'Electro'],
    seats: [
      { id: 0, userId: MOCK_USERS[2].id, user: MOCK_USERS[2], isMuted: false, isLocked: false, isSpeaking: true, speakingVolume: 90, title: 'King 👑' },
      { id: 1, userId: CURRENT_USER.id, user: CURRENT_USER, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0, title: 'VIP' },
      { id: 2, userId: MOCK_USERS[1].id, user: MOCK_USERS[1], isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 3, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 4, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 5, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 6, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 7, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
    ],
  },
  {
    id: 'room_103',
    title: '🎧 Chill Acoustics & Late Night Story 🌌',
    notice: 'Soft conversations and chill acoustic guitars. Share your stories with us.',
    host: MOCK_USERS[3],
    category: 'Late Night',
    bgTheme: 'ocean_blue',
    bgmPlaying: false,
    isLocked: false,
    onlineCount: 175,
    giftValueToday: 9400,
    tags: ['Acoustic', 'Stories', 'Chill', 'Sleep'],
    seats: [
      { id: 0, userId: MOCK_USERS[3].id, user: MOCK_USERS[3], isMuted: false, isLocked: false, isSpeaking: true, speakingVolume: 40, title: 'Host' },
      { id: 1, userId: MOCK_USERS[4].id, user: MOCK_USERS[4], isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 2, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 3, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 4, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 5, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 6, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
      { id: 7, userId: null, isMuted: false, isLocked: false, isSpeaking: false, speakingVolume: 0 },
    ],
  },
];
